name: Tweet Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 4 * * *'
    - cron: '0 6 * * *'
    - cron: '0 8 * * *'
    - cron: '0 10 * * *'
    - cron: '0 12 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
    - cron: '0 20 * * *'
    - cron: '0 22 * * *'
jobs:
  run_script:
    runs-on: ubuntu-latest  # Runs on a Linux virtual machine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Pulls your code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install tweepy  # Install your script dependencies
          pip install openai
          pip install python-dotenv

      - name: Run the script
        run: |
          python TweetPoster.py  

        
